NAME : DIYA THAKKAR 
ID : 22000559
SYBCA BATCH-A

In [1]:
import numpy as np


In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.ones(10)*5


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [6]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [7]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.random.randn(1)

array([-0.54182179])

In [10]:
np.random.randn(25)

array([-1.4802431 , -0.31005352,  0.54949229,  0.15845687,  0.15536917,
       -0.42244286,  0.06701983, -0.99269724, -0.06218303, -0.61348493,
        1.36532349, -2.68472984,  0.17535963, -0.16935268,  0.38634792,
        1.32148617,  0.51414834, -1.23494724,  1.261171  , -0.96657272,
       -0.13653228, -0.35558861, -0.92608754,  2.2643861 , -1.36367251])

In [11]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [12]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [13]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
np.arange(12,26)


array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [15]:
import numpy as np
a=np.arange(1,26).reshape(5,5)

In [16]:
a[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [17]:
import numpy as np
a=np.arange(1,26).reshape(5,5)
a[1:,2:]

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [18]:
import numpy as np
a=np.arange(1,26).reshape(5,5)
a[3:4,4:]

array([[20]])

In [19]:
import numpy as np
a=np.arange(1,26).reshape(5,5)
a[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [20]:
import numpy as np
a=np.arange(1,26).reshape(5,5)
a[4]

array([21, 22, 23, 24, 25])

In [21]:
import numpy as np
a=np.arange(1,26).reshape(5,5)
a[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [22]:
import numpy as np
a=np.arange(1,26).reshape(5,5)
a[2:,2:3]

array([[13],
       [18],
       [23]])

In [23]:
sum(a)

array([55, 60, 65, 70, 75])

In [24]:
a.sum()

325

In [25]:
a.std()

7.211102550927978

In [26]:
a.sum(axis=0)

array([55, 60, 65, 70, 75])

In [27]:
a.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [28]:
a=np.arange(1,13).reshape(3,2,2)
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [29]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [30]:
c=np.arange(1,5).reshape(2,2)
c

array([[1, 2],
       [3, 4]])

In [31]:
c.dtype

dtype('int32')

In [32]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.ones(4).reshape(2,2)

array([[1., 1.],
       [1., 1.]])

In [35]:
maths_marks=np.random.randint(1,100,20)
maths_marks


array([34,  7, 47, 99, 84, 18, 38, 57, 30, 61, 91, 16,  9, 79,  6, 15, 19,
       87, 75, 45])

In [36]:
maths_marks=34,  7, 47, 99, 84, 18, 38, 57, 30, 61, 91, 16,  9, 79,  6, 15, 19, 87, 75, 45
np.sort(maths_marks)

array([ 6,  7,  9, 15, 16, 18, 19, 30, 34, 38, 45, 47, 57, 61, 75, 79, 84,
       87, 91, 99])

In [39]:
asc= 6,  7,  9, 15, 16, 18, 19, 30, 34, 38, 45, 47, 57, 61, 75, 79, 84, 87, 91, 99
np.flip(asc)

array([99, 91, 87, 84, 79, 75, 61, 57, 47, 45, 38, 34, 30, 19, 18, 16, 15,
        9,  7,  6])

In [40]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
np.eye(5,5).reshape(25)

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [43]:
np.eye(5,5).ravel()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [44]:
np.eye(5,5).flatten()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [45]:
mat=np.arange(0,9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
np.append(mat,[[9,10,11]],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [47]:
np.split?

In [48]:
x=np.arange(0,9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [54]:
np.split(x,3,axis=0)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [56]:
v=np.arange(0,9)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [57]:
v=mat
v

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
np.split(v,3,axis=1)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [59]:
np.random.uniform?


In [60]:
np.random.uniform(-1,0,10)

array([-0.63251045, -0.59361875, -0.14634626, -0.19180902, -0.79727455,
       -0.09821211, -0.973801  , -0.33120426, -0.87163757, -0.85708099])

In [64]:
s=np.random.uniform(0,9,10)
s

array([0.2347903 , 6.25831511, 2.61658351, 4.7279608 , 8.7391744 ,
       8.02785644, 8.44560437, 1.08961131, 3.83032375, 3.27871346])

In [65]:
np.ceil(s)

array([1., 7., 3., 5., 9., 9., 9., 2., 4., 4.])

In [67]:
np.floor(s)

array([0., 6., 2., 4., 8., 8., 8., 1., 3., 3.])

In [68]:
np.round(s,decimals=2)

array([0.23, 6.26, 2.62, 4.73, 8.74, 8.03, 8.45, 1.09, 3.83, 3.28])

In [69]:
np.eye(4)+4

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [76]:
h=np.arange(0,25).reshape(5,5)
h

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [82]:
z=np.ones((10,10))
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [84]:
z[1:9,1:9]=0

In [85]:
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [89]:
p=np.zeros((8,8),dtype                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             =int)
p[::2,::2]=1
p[1::2,1::2]=1
p

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [3]:
5*5 matix 0 to 25 add row and split

SyntaxError: invalid syntax (2569440946.py, line 1)

In [17]:
a=np.arange(0,25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
np.append(a,[[1,2,3,4,5]],axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [ 1,  2,  3,  4,  5]])

In [26]:
np.vsplit(a,5)

[array([[0, 1, 2, 3, 4]]),
 array([[5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24]])]